### ISSUE TITLE
deploy on heroku but not found default login info

### ISSUE THREAD

**Issue by todokku** [MitsukiGoto/YoutubeProxyLikeServer#9]
Hi Mitsuki,
https://youtubeproxyserver.herokuapp.com/
deploy on heroku but not found login info
ユーザー名：?
パスワード：?
waiting for your response
finest regards
goodbye

**Comment by MitsukiGoto** [comment]
Sorry. this app is developed for my friends. ):
My school don’t let us watch Youtube.
Thanks for wanting to use.

**Comment by MitsukiGoto** [comment]
So to use this app, please fork this and deploy your self.

**Comment by MitsukiGoto** [comment]
Oh, sorry I commented something strange

**Comment by MitsukiGoto** [comment]
First,run “from src import models; models.init_db()” 
in heroic

**Comment by MitsukiGoto** [comment]
First add add-on https://elements.heroku.com/addons/heroku-postgresql hobby rev or after

**Comment by MitsukiGoto** [comment]
Second, run “from src import models; models.init_db()” on heroku

**Comment by MitsukiGoto** [comment]
Sorry, master branch dev does not work for you

**Comment by MitsukiGoto** [comment]
Because pytube sometimes raises KeyError

**Comment by MitsukiGoto** [comment]
Latest dev is . PyTube2YouToubeDl 
So, please fork it instead of master

**Comment by todokku** [comment]
hello again , 
deployed latest version of PyTube2YouToubeDl but after click on register get internal error below :

**Comment by MitsukiGoto** [comment]
show me the log please

**Comment by todokku** [comment]
here is my dyno logs :
https://gist.github.com/todokku/bfaee869d724de9ee33de0c8ecc4c836

**Comment by MitsukiGoto** [comment]
thank u
It comes from not creating database
see ReadMe.md to create databse and user account

**Comment by todokku** [comment]
hello again ,

at the first thanks for update readme.md file ,
in the section below :
open heroku console run python code

    from src import models
    models.init_db()

* heroku consule commands are not work in consule or bash in the my dyno panel 
please if its possible make this code autopilot in your main source ,

waiting for your response
finest regards
goodbye

**Comment by MitsukiGoto** [comment]
OK. Just a minute.

**Comment by todokku** [comment]
waiting for your response
please don't forget me :(
finest regards
goodbye

**Comment by todokku** [comment]
hellllowww , 
Mitsuki please make app.json file for easy deploy project on heroku ,
waiting for your response
finest regards
goodbye

**Comment by MitsukiGoto** [comment]
What’s that?

**Comment by MitsukiGoto** [comment]
auto intializing database doesn't work well

**Comment by todokku** [comment]
after run this :
python -c "user = models.Registered_User(user_name=admin, password=fb001dfcffd1c899f3297871406242f097aecf1a5342ccf3ebcd116146188e4b);
models.db.session.add(user); models.db.session.commit()"
get error in consule :
file "<string>", line 1, in <module>
NameError: name 'models' is not defined
fb001dfcffd1c899f3297871406242f097aecf1a5342ccf3ebcd116146188e4b == SHA3-256 of "admin"
waiting for your response
finest regards
goodbye

**Comment by MitsukiGoto** [comment]
Ah, Sorry

that was an in-correct command

correct one: 

Here's how you would do it:
~~~
heroku run python -c "import src.models; user = models.Registered_User(user_name=admin, password=fb001dfcffd1c899f3297871406242f097aecf1a5342ccf3ebcd116146188e4b);
models.db.session.add(user); models.db.session.commit()"
~~~

**Comment by MitsukiGoto** [comment]
I'll update ReadMe.md as soon as you confirm that

**Comment by todokku** [comment]
Hello Again Mitsuki , 
sorry for too late response ,
this command not work : 
python -c "import src.models; user = models.Registered_User(user_name=admin, password=fb001dfcffd1c899f3297871406242f097aecf1a5342ccf3ebcd116146188e4b);
models.db.session.add(user); models.db.session.commit()"
& give this error :
NameError: name 'models' is not defined
please if its possible remove lin section & access free to use
waiting for your response
finest regards

**Comment by MitsukiGoto** [comment]
Hi, todokku.

that was wrong, sorry.

Correct one

~~~
python -c "from src import models; user = models.Registered_User(user_name=admin, password=fb001dfcffd1c899f3297871406242f097aecf1a5342ccf3ebcd116146188e4b);
models.db.session.add(user); models.db.session.commit()"
~~~

**Comment by todokku** [comment]
Hello Again Mitsuki ,
your new command not work :
python -c "from src import models; user = models.Registered_User(user_name=admin, password=fb001dfcffd1c899f3297871406242f097aecf1a5342ccf3ebcd116146188e4b);
models.db.session.add(user); models.db.session.commit()"
give error :
File "<string>", line 1,in <module>
NameError: name 'admin' is not defined
waiting for your response
finest regards

**Comment by MitsukiGoto** [comment]
you have to type username with double quotation

**Comment by todokku** [comment]
Hello Again Mitsuki ,
with type username & password in double quotation & single qoutation giving error ,
better than this must be you test commands on heroku consule & after wel done worked , put them here ,
waiting for your response
finest regards

**Comment by MitsukiGoto** [comment]
Ok , sorry for not testing

**Comment by MitsukiGoto** [comment]
Am, did you make database well?

**Comment by todokku** [comment]
Hello Again Mitsuki ,
yeah make database well 
please if its possible make remove login section of your script
waiting for your response
finest regards

**Comment by todokku** [comment]
Hello Again Mitsuki ,
can you dockerise this project for easy deploy it without error ?
waiting for your response
finest regards

**Comment by MitsukiGoto** [comment]
Hi, todokku.
Recently, i cannot maintain or new dev because my study is so busy.
please make what you think by yourself
